/* Generated by cbindgen — do not edit */

#ifndef CAULDRON_H
#define CAULDRON_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Initialize a CauldronEngine rooted at the given base directory.
 * Returns an opaque pointer to the engine, or null on failure.
 */
void *cauldron_init(const char *base_dir);

/**
 * Free a CauldronEngine previously created by `cauldron_init`.
 */
void cauldron_free(void *ptr);

/**
 * Initialize the game database at the given path. Returns 0 on success, -1 on failure.
 */
int32_t cauldron_init_db(const char *path);

/**
 * Query a single game by Steam app ID. Returns a JSON string or null.
 * The returned string must be freed with `cauldron_free_string`.
 */
char *cauldron_query_game(void *mgr, uint32_t app_id);

/**
 * List all games in the database as a JSON array.
 * Returns seed data as a placeholder if the database is empty.
 * The returned string must be freed with `cauldron_free_string`.
 */
char *cauldron_list_games(void *mgr);

/**
 * Get the current sync pipeline status as JSON.
 * The returned string must be freed with `cauldron_free_string`.
 */
char *cauldron_get_sync_status(void *mgr);

/**
 * Get available Wine versions as a JSON array of WineVersion objects.
 * The returned string must be freed with `cauldron_free_string`.
 */
char *cauldron_get_wine_versions(void *mgr);

/**
 * Download and install a Wine version. Returns a JSON object with
 * `{"success": true, "path": "..."}` or `{"success": false, "error": "..."}`.
 * This is a blocking call. The returned string must be freed with `cauldron_free_string`.
 */
char *cauldron_download_wine(void *mgr, const char *version);

/**
 * Get all installed Wine versions as a JSON array with paths.
 * The returned string must be freed with `cauldron_free_string`.
 */
char *cauldron_get_installed_wine(void *mgr);

/**
 * Scan a bottle for detected games. Returns a JSON array of game records.
 * The returned string must be freed with `cauldron_free_string`.
 */
char *cauldron_scan_bottle_games(void *mgr, const char *bottle_id);

/**
 * Create a new bottle. Returns a JSON string describing the bottle, or null on failure.
 * The returned string must be freed with `cauldron_free_string`.
 */
char *cauldron_create_bottle(void *mgr, const char *name, const char *wine_version);

/**
 * List all bottles as a JSON array string.
 * The returned string must be freed with `cauldron_free_string`.
 */
char *cauldron_list_bottles(void *mgr);

/**
 * Delete a bottle by its ID. Returns 0 on success, -1 on failure.
 */
int32_t cauldron_delete_bottle(void *mgr, const char *id);

/**
 * Discover existing Wine bottles from other applications (Whisky, CrossOver, etc.).
 * Returns a JSON array of discovered bottles, or null on failure.
 * The returned string must be freed with `cauldron_free_string`.
 */
char *cauldron_discover_bottles(void *_mgr);

/**
 * Import a discovered bottle by its source path. Creates a symlink in Cauldron's
 * bottles directory and writes a proper bottle.toml so it appears in the bottle list.
 * Returns the imported Bottle as JSON, or null on failure.
 * The returned string must be freed with `cauldron_free_string`.
 */
char *cauldron_import_bottle(void *mgr, const char *source_path, const char *name);

/**
 * Run a full sync cycle: fetch Proton commits, classify, adapt, apply patches, and
 * record results in the database. Returns updated SyncStatus JSON.
 * This is a blocking call — the Swift side should call it from Task.detached.
 * The returned string must be freed with `cauldron_free_string`.
 */
char *cauldron_run_sync(void *mgr);

/**
 * Launch an executable inside a bottle using Wine.
 * Returns 0 on success (process spawned), -1 on failure.
 */
int32_t cauldron_launch_exe(void *mgr,
                            const char *bottle_id,
                            const char *exe_path,
                            const char *backend);

/**
 * Free a string previously returned by any `cauldron_*` function.
 */
void cauldron_free_string(char *s);

/**
 * Analyze all pending patches: dry-run, impact score, affected games, ProtonDB.
 * Returns JSON array of PatchAnalysis objects.
 */
char *cauldron_analyze_patches(void *mgr);

/**
 * Trigger a Wine build verification in the background.
 * Returns JSON with success/error. The build runs `make -j` in wine_source_dir.
 */
char *cauldron_verify_build(void *mgr);

/**
 * Query proton commits with optional filter. Returns JSON array.
 */
char *cauldron_get_proton_commits(void *mgr, const char *filter, uint32_t limit);

/**
 * Apply a single patch by commit hash. Returns JSON with success/error.
 */
char *cauldron_apply_patch(void *mgr, const char *hash);

/**
 * Skip a patch by commit hash. Returns JSON with success/error.
 */
char *cauldron_skip_patch(void *mgr, const char *hash);

/**
 * Reverse an applied patch via git revert. Returns JSON with success/error.
 */
char *cauldron_reverse_patch(void *mgr, const char *hash);

char *cauldron_detect_d3dmetal(void *_mgr);

char *cauldron_setup_dlss_metalfx(void *mgr, const char *bottle_id);

char *cauldron_import_d3dmetal(void *_mgr, const char *_path);

char *cauldron_detect_rosettax87(void *_mgr);

char *cauldron_scan_game_patches(void *_mgr, const char *_bid);

char *cauldron_apply_game_patch(void *_mgr, const char *_exe);

char *cauldron_restore_game_exe(void *_mgr, const char *_exe);

char *cauldron_list_known_game_patches(void *_mgr);

char *cauldron_seed_game_profiles(void *_mgr);

char *cauldron_get_game_recommendation(void *_mgr, uint32_t _app_id);

char *cauldron_download_all_runtimes(void *_mgr);

char *cauldron_list_dependencies(void *_mgr);

char *cauldron_install_dependency(void *_mgr, const char *_bid, const char *_dep);

/**
 * Returns 1 if bottle is running, 0 if not, -1 on error.
 * STUB: always returns 0 (not running) — needs proper process tracking.
 */
int32_t cauldron_is_bottle_running(void *_mgr, const char *_bid);

/**
 * Kill Wine processes for a bottle. Returns 0 on success, -1 on failure.
 */
int32_t cauldron_kill_bottle(void *_mgr, const char *_bid);

/**
 * Switch a bottle's graphics backend (stub — backend switching now handled via env vars at launch).
 */
char *cauldron_switch_backend(void *_mgr,
                              const char *_bottle_id,
                              const char *_backend);

#endif  /* CAULDRON_H */
